# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Authorization: Basic MTIzOjQ1Ng==
Accept: application/json

###

GET http://127.0.0.1:8000/users/me
Authorization: Basic MTIzOjQ1Ng==
Accept: application/json


###
